# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 570, 336))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.input_field = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_field.sizePolicy().hasHeightForWidth())
        self.input_field.setSizePolicy(sizePolicy)
        self.input_field.setMinimumSize(QtCore.QSize(0, 100))
        self.input_field.setMaximumSize(QtCore.QSize(16777215, 100))
        self.input_field.setObjectName("input_field")
        self.verticalLayout.addWidget(self.input_field)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxTranslateTo = QtWidgets.QComboBox(self.frame)
        self.comboBoxTranslateTo.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxTranslateTo.setObjectName("comboBoxTranslateTo")
        self.comboBoxTranslateTo.addItem("")
        self.comboBoxTranslateTo.addItem("")
        self.comboBoxTranslateTo.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxTranslateTo)
        self.search_button = QtWidgets.QPushButton(self.frame)
        self.search_button.setMinimumSize(QtCore.QSize(0, 30))
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My Application"))
        self.input_field.setPlaceholderText(_translate("MainWindow", "Enter text to translate"))
        self.label.setText(_translate("MainWindow", "Translate To"))
        self.comboBoxTranslateTo.setToolTip(_translate("MainWindow", "Translate To"))
        self.comboBoxTranslateTo.setItemText(0, _translate("MainWindow", "Arabic"))
        self.comboBoxTranslateTo.setItemText(1, _translate("MainWindow", "English"))
        self.comboBoxTranslateTo.setItemText(2, _translate("MainWindow", "Frensh"))
        self.search_button.setText(_translate("MainWindow", "Translate"))
